### ISSUE TITLE
Cannot see the source functions

### ISSUE THREAD

**Issue by eleozzr** [feiyoung/ILSE#1]
Hi feiyoung, 
    I found the open-source package did include the original R script and the related functions, could you publish them to help us to understand your paper better. Thanks.

**Comment by feiyoung** [comment]
Hi, Xiangjie,
&nbsp;The source package is on the computer in my school, but now all students in our school are studying at home due to COVID-19. I will publish the source package&nbsp;or send it to you if I go to school.



Sincerely,

Center of Statistical Research &amp; School of Statistics
Southwestern University of Finance and Economics 
Chendu, China



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangjie Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 晚上9:20
收件人:&nbsp;"feiyoung/ILSE"<ILSE@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[feiyoung/ILSE] Cannot see the source functions (#1)





 
Hi feiyoung,
 I found the open-source package did include the original R script and the related functions, could you publish them to help us to understand your paper better. Thanks.

**Comment by eleozzr** [comment]
Hi feiyoung,
   I have already found the related functions in your packaged R environment. Thank you very much. Have a good day.



Best
Xixiangjie














在 2020-04-01 08:09:37，"Wei Liu" <notifications@github.com> 写道：

Hi, Xiangjie,
&nbsp;The source package is on the computer in my school, but now all students in our school are studying at home due to COVID-19. I will publish the source package&nbsp;or send it to you if I go to school.



Sincerely,

Center of Statistical Research &amp; School of Statistics
Southwestern University of Finance and Economics
Chendu, China



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangjie Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月19日(星期四) 晚上9:20
收件人:&nbsp;"feiyoung/ILSE"<ILSE@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[feiyoung/ILSE] Cannot see the source functions (#1)






Hi feiyoung,
I found the open-source package did include the original R script and the related functions, could you publish them to help us to understand your paper better. Thanks.

**Comment by feiyoung** [comment]
Ok! That's good!&nbsp;

Best!

Center of Statistical Research &amp; School of Statistics
Southwestern University of Finance and Economics 
Chendu, China



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Xiangjie Li"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月1日(星期三) 上午8:16
收件人:&nbsp;"feiyoung/ILSE"<ILSE@noreply.github.com&gt;;
抄送:&nbsp;"刘伟"<1029725413@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [feiyoung/ILSE] Cannot see the source functions (#1)





 Hi feiyoung,
    I have already found the related functions in your packaged R environment. Thank you very much. Have a good day.
 
 
 
 Best
 Xixiangjie
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 在 2020-04-01 08:09:37，"Wei Liu" <notifications@github.com&gt; 写道：
 
 Hi, Xiangjie,
 &amp;nbsp;The source package is on the computer in my school, but now all students in our school are studying at home due to COVID-19. I will publish the source package&amp;nbsp;or send it to you if I go to school.
 
 
 
 Sincerely,
 
 Center of Statistical Research &amp;amp; School of Statistics
 Southwestern University of Finance and Economics
 Chendu, China
 
 
 
 &amp;nbsp;
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人:&amp;nbsp;"Xiangjie Li"<notifications@github.com&amp;gt;;
 发送时间:&amp;nbsp;2020年3月19日(星期四) 晚上9:20
 收件人:&amp;nbsp;"feiyoung/ILSE"<ILSE@noreply.github.com&amp;gt;;
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;;
 主题:&amp;nbsp;[feiyoung/ILSE] Cannot see the source functions (#1)
 
 
 
 
 
 
 Hi feiyoung,
 I found the open-source package did include the original R script and the related functions, could you publish them to help us to understand your paper better. Thanks.

**Comment by feiwsteven** [comment]
The R package has no R source codes. Can you update the git?

**Comment by eleozzr** [comment]
> The R package has no R source codes. Can you update the git?

Hi, you can use `lazyLoad` function to get the R script 
```r
lazyLoad("ILSE")
ls()
#after ls(),you will see all source codes.
```

**Comment by JustToBeYourself** [comment]
I noticed that the correlation of some covariates in this paper is high, so is there any doubt about the significance of the parameters obtained in this paper? And I am curious that if the algorithm could be extended to certain regular conditions,such as lasso?
